### ISSUE TITLE
Compile with CMake failed, version 2.49.0

### ISSUE THREAD

**Issue by Berrysoft** [git-for-windows/git#5532]
I was trying to compile the latest git-for-windows with MSYS2 mingw environment and cmake buildsystem, but MINGW64 & UCRT64 failed with same reason, while CLANG64 and CLANGARM64 succeeded:
```
FAILED: t/unit-tests/bin/unit-tests.exe 
C:\Windows\system32\cmd.exe /C "cd . && C:\msys64\mingw64\bin\gcc.exe -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -DNDEBUG -municode -Wl,--nxcompat -Wl,--dynamicbase -Wl,--pic-executable,-e,mainCRTStartup CMakeFiles/common-main.dir/D_/a/1/s/mingw-w64-git/src/git-2.49.0.windows.1/common-main.c.obj -o t\unit-tests\bin\unit-tests.exe -Wl,--out-implib,libunit-tests.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libunit-tests-lib.a  libclar-test-lib.a  liblibgit.a  libxdiff.a  libreftable.a  C:/msys64/mingw64/lib/libz.dll.a  C:/msys64/mingw64/lib/libintl.dll.a  C:/msys64/mingw64/lib/libiconv.dll.a  -lpcre2-8  -lws2_32  -lntdll  git.res  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.data+0x50): undefined reference to `test_example_decorate__initialize'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.data+0x60): undefined reference to `test_example_decorate__cleanup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x19c8): undefined reference to `test_ctype__isspace'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x19d8): undefined reference to `test_ctype__isdigit'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x19e8): undefined reference to `test_ctype__isalpha'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x19f8): undefined reference to `test_ctype__isalnum'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a08): undefined reference to `test_ctype__is_glob_special'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a18): undefined reference to `test_ctype__is_regex_special'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a28): undefined reference to `test_ctype__is_pathspec_magic'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a38): undefined reference to `test_ctype__isascii'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a48): undefined reference to `test_ctype__islower'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a58): undefined reference to `test_ctype__isupper'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a68): undefined reference to `test_ctype__iscntrl'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a78): undefined reference to `test_ctype__ispunct'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a88): undefined reference to `test_ctype__isxdigit'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libclar-test-lib.a(clar.c.obj):clar.c:(.rdata+0x1a98): undefined reference to `test_ctype__isprint'

collect2.exe: error: ld returned 1 exit status
```

I tried the command directly, and found that the same gcc command and args succeeded in a normal windows shell, but failed in a MSYS2 shell. The command also failed inside CI.

**Comment by Berrysoft** [comment]
Might be related: https://github.com/msys2/MINGW-packages/issues/23708

**Comment by dscho** [comment]
@Berrysoft Git for Windows is not meant to be compiled with CMake and GCC. It is meant to be compiled with _`make`_ and `gcc`.

The CMake support is only meant to support building with Visual Studio, and that support is too tedious to maintain _against_ upstream Git (who do a great job of making this harder than necessary) and therefore I plan on dropping support to build Git with Visual Studio.

In other words, please use regular `make`.

If you _must_ use a different build system, use `meson`. That's the direction upstream Git is going anyway.

**Comment by Berrysoft** [comment]
Thank you. So do you think the problem is caused by cmake?

**Comment by dscho** [comment]
> Thank you. So do you think the problem is caused by cmake?

It is caused by an incomplete CMake definition. As I said, it's too much work to support properly. Please do not use CMake to build Git for Windows, not when you want to compile in an MSYS2 environment.

**Comment by Berrysoft** [comment]
I would like to take your advice, but could you explain more about the incomplete definitions?

**Comment by dscho** [comment]
> I would like to take your advice, but could you explain more about the incomplete definitions?

@Berrysoft my main aim, as I have stated, is _not_ to spend more effort on this. Therefore I will answer this one last question about CMake and then I will do that no more.

Git's `make`-based build has tons of settings. See https://github.com/git-for-windows/git/blob/v2.49.0.windows.1/Makefile#L14-L601. Almost none of these build-time settings are supported in the [`CMakeLists.txt` file](https://github.com/git-for-windows/git/blob/v2.49.0.windows.1/contrib/buildsystems/CMakeLists.txt).

**Comment by Berrysoft** [comment]
Thank you very much. I'm switching to meson.
