### ISSUE TITLE
Git TF does not work with Git 2.5

### ISSUE THREAD

**Issue by regisbsb** [git-for-windows/git#283]
I've installed Git 2.5 but now the Git-tf command does not work anymore.
I know that Git-tf is from Microsoft but it looks a bit abandoned. Now that the Git for windows is getting some help from microsoft it would be good to port Git-tf to Github and maybe make then compatible? 

More to the problem I think it is the way git 2.5 calls the plugins like "tf" passing to many parameters.

See message below:

    C:>git tf help 
    C:\Program Files (x86)\git-tf\git-tf: line 66: [: too many arguments 
    Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/gittf/client/clc/Main 
    Caused by: java.lang.ClassNotFoundException: com.microsoft.gittf.client.clc.Main
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
    Could not find the main class: com.microsoft.gittf.client.clc.Main. Program will exit.

https://gittf.codeplex.com/

**Comment by dscho** [comment]
Would you please indicate where you got this `git-tf` from, and which version you tried to get to run?

**Comment by regisbsb** [comment]
From the link in the issue i've navigated to https://gittf.codeplex.com/releases/view/116074 and got 2.0.3.1 git tf
It's the latest. It was working with the git 1.9.5 but it stopped working after i've changed to git 2.5

**Comment by dscho** [comment]
Looks like some shell script syntax that Bash does not like, and as a consequence the classpath is constructed incorrectly.

**Comment by regisbsb** [comment]
Git should call git-tf as it was before, is it possible to compare?

**Comment by dscho** [comment]
@regisbsb why don't you paste what line 66 looks like? Maybe with context? I mean, you can also wait until I am done with other things and then I will go and download it myself and have a look. But you could also help me to help you.

**Comment by regisbsb** [comment]
Yes for sure.
You mean the java source code? I can get that from codeplex for sure:
https://gittf.codeplex.com/SourceControl/changeset/view/22c22f85983f19e9f4e4d787edf03bfb42b19284#com.microsoft.gittf.client.clc/src/main/java/com/microsoft/gittf/client/clc/Main.java

**Comment by regisbsb** [comment]
I don't know the git plugin architecture but is it possible to create a git-test.cmd that just outputs it's parameters to a log file and put that in your path and compare with what I get?

**Comment by dscho** [comment]
I think you were talking about

https://gittf.codeplex.com/SourceControl/changeset/view/22c22f85983f19e9f4e4d787edf03bfb42b19284#com.microsoft.gittf.client.clc/scripts/git-tf

instead, and the offending line 66 reads:

```sh
if [ ! -f $TEST_REQUIRED_JAR ]; then
```

The context is:

```sh
# Ensure that our main JAR exists
TEST_REQUIRED_JAR="$BASE_DIRECTORY/lib/com.microsoft.gittf.client.clc-*.jar"
if [ ! -f $TEST_REQUIRED_JAR ]; then
    echo "Unable to find a required JAR: $TEST_REQUIRED_JAR does not exist"
    exit
fi
```

**Comment by regisbsb** [comment]
I've tried everything from creating a git-test.cmd modifing the git-tf.cmd but I did not have success finding out how to output apart from adding a `pause` and inspecting with processxp. 
Apparently git calls itself that calls sh that calls git-tf:
git  tf
git.exe  tf
"C:\Program Files (x86)\Git\bin\sh.exe" "C:\Program Files (x86)\Git\cmd\git-tf"
c:\Windows\system32\cmd.exe /C git-tf.cmd

**Comment by regisbsb** [comment]
If it could not find the jar it would say so.
It's finding the jar but it's passing more parameters than it should somehow.

**Comment by regisbsb** [comment]
exec java -Xmx512m -classpath "$GITTF_CLASSPATH" \
       "-Dcom.microsoft.tfs.jni.native.base-directory=$BASE_DIRECTORY/native" \
       com.microsoft.gittf.client.clc.Main "$@"

**Comment by dscho** [comment]
`git tf` calls `git-tf`, not `git-tf.cmd`. That might be what is haunting you :smiley:

**Comment by regisbsb** [comment]
so it's definitively the variables that are passed to the git-tf (not .cmd) script are different from 1.9.5 from 2.5.... if only I knew how to debug the shell script! I cannot understand then why would it behave diferently. because apparently git-tf calls git-tf.cmd

**Comment by dscho** [comment]
> Git should call git-tf as it was before, is it possible to compare?

The easiest way to compare is to call the script directly, using Bash's `-x` option, like so:

```sh
sh -x /path/to/git-tf <arguments...>
```

If you do that with 1.9.5 and with 2.5.0 and capture the output of both (e.g. by appending ` 2>&1 | tee out1.log`), it should be relatively easy to see from a diff where things go wrong.

**Comment by regisbsb** [comment]
Cheers, I'll try at work tomorrow.

**Comment by Radrik5** [comment]
Add double quotes around $TEST_REQUIRED_JAR:

    if [ ! -f "$TEST_REQUIRED_JAR" ]; then

**Comment by dscho** [comment]
@Radrik5 I agree, but then, `TEST_REQUIRED_JAR` is not empty, according to the context of the script. So I really would like to see better what the hex is going on.

**Comment by Radrik5** [comment]
`TEST_REQUIRED_JAR` probably contains space, so the `[` command gets more arguments than it should.

**Comment by Radrik5** [comment]
With double quotes asterisk in `TEST_REQUIRED_JAR` will not work, so the `if` statement should be rewritten.
http://stackoverflow.com/questions/6363441/check-if-a-file-exists-with-wildcard-in-shell-script

**Comment by dscho** [comment]
> TEST_REQUIRED_JAR probably contains space

That's probably the reason, indeed.

**Comment by regisbsb** [comment]
Is it because the new git uses a different kind of unix "cmd" or settings? Because this same script worked before on the old git 1.x

**Comment by dscho** [comment]
Let's move this discussion to https://gittf.codeplex.com/SourceControl/network/forks/dscho/gittf/contribution/8444 which contains my suggested fixes.

**Comment by regisbsb** [comment]
Thank you so much.
I've tested and it works very well!!!
While not merged for people that use TFS please update the Git-tf file as:
https://gittf.codeplex.com/SourceControl/network/forks/dscho/gittf/latest#com.microsoft.gittf.client.clc/scripts/git-tf

**Comment by dscho** [comment]
It has been merged, but I have no idea when the next release is coming. In the meantime, downloading the bash script individually will work.

**Comment by regisbsb** [comment]
Cool
